name: Deploy

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install dependencies
      run: npm ci

    - name: Build project
      run: npm run build

    - name: Deploy Contember to production
      run: npm run contember deploy ${{ secrets.CONTEMBER_DSN }} -- --yes
      